---
- name: "Check For Secrets"
  assert:
    that:
      - secrets['bind-username'] is defined
      - secrets['bind-password'] is defined
    fail_msg: "common/ansible/roles/realmd-configure expects bind-username and bind-password secrets are defined"

- name: "Check if machine is already bound"
  shell: "realm list"
  register: realm_list_output
  changed_when: false
  failed_when: false

- name: "Join system to AD"
  expect:
    command: "/usr/sbin/realm join \
      --membership-software=adcli \
      --server-software=active-directory \
      --client-software=sssd \
      --computer-ou=ou={{ env_type }},OU=ASH,OU=OCI,OU=Servers,DC=my,DC=domain \
      --user={{ secrets['bind-username'] }} \
      my.domain"
    responses:
      (?i)Password for *: "{{ secrets['bind-password'] }}"
    timeout: 300
  retries: 10
  delay: "{{ 60 | random }}"
  register: realm_join_output
  until: realm_join_output is success
  when: not realm_list_output.stdout is search('my.domain')

- name: "Include vars based on env_type and env_name"
  include_vars: "{{ item }}"
  with_first_found: ['{{ env_type }}-{{ env_name }}.yaml', '{{ env_type }}.yaml', 'default.yaml']

- name: "Add sudoers"
  template:
    src: "sudoers_my_domain.j2"
    dest: "/etc/sudoers.d/my_domain"
    owner: "root"
    group: "root"
    lstrip_blocks: yes

- name: "Modify SSSD Configuration"
  copy:
    src: "sssd.conf"
    dest: "/etc/sssd/sssd.conf"

- name: "Restart SSSD Service"
  service:
    name: "sssd"
    state: restarted

- name: "Modify SSH Configuration"
  copy:
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
  register: sshd_config_change_output

- name: "Restart SSH Service"
  service:
    name: "sshd"
    state: reloaded
  when: sshd_config_change_output.changed | bool
