---
ansible_ssh_user: "opc"
ansible_ssh_private_key_file: "~/.ssh/oci_private_key"

default_server_name: "yum"
instance_ad: "sSxD:US-ASHBURN-AD-1"
instance_shape: "VM.Standard.E2.1"
instance_hostname: "{{ env_name }}-{{ server_name }}"

metadata_base_path: "/home/tomcat/instances/{{ env_type }}/{{ env_name }}/"

firewall_allow_ports: 
  - "80/tcp"
