---
- hosts:
    - "{{ arg_env_type }}_{{ arg_instance_role }}"
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name | default(default_server_name) }}"
    instance_ad: "{{ arg_instance_ad }}"
    jenkins_user: "{{ arg_jenkins_user }}"
  roles:
    - common.oci-vars
    - oci-format-volume
  environment:
    OCI_ANSIBLE_AUTH_TYPE: "instance_principal"
