---
- hosts:
    - cloudflare
  vars:
    record_name: "{{ arg_record_name }}"
    record_value: "{{ arg_record_value }}"
  roles:
    - common.oci-vars
    - common.vault-get-secrets
    - remove-dns-cloudflare
