---
- hosts:
    - dnsmadeeasy
  vars:
    record_name: "{{ arg_record_name }}"
    record_type: "{{ arg_record_type }}"
    record_value: "{{ arg_record_value }}"
  roles:
    - common.oci-vars
    - common.vault-get-secrets
    - update-dns-dnsmadeeasy
