---
- hosts:
    - uat
  vars_files:
    - "{{ arg_configuration_file }}"
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name }}"
  roles:
    - common.oci-vars
    - loadbalancer-facts
    - backendsets-create
    - rulesets-create
    - generic-listeners-create
  tasks:
    - name: "Include the roles to add each required url to the loadbalancer"
      include_role:
        name: url-update
      with_items: "{{ default_urls + additional_urls }}"
      vars:
        url_name: "{{ item.name }}"
        url_domain: "{{ item.domain }}"

- hosts:
    - static
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name }}"
  roles:
    - common.oci-vars
    - loadbalancer-facts
    - backendsets-create
    - rulesets-create
    - generic-listeners-create
  tasks:
    - name: "Include the roles to add each required url to the loadbalancer"
      include_role:
        name: url-update
      with_items: "{{ default_urls + additional_urls }}"
      vars:
        url_name: "{{ item.name }}"
        url_domain: "{{ item.domain }}"
