---
- name: "Install the PGBouncer RPM"
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    lock_timeout: 180

- name: "Install PGBouncer Server Package"
  yum:
    name: pgbouncer
    state: present
    lock_timeout: 180
