---
- name: "Launch an instance"
  delegate_to: localhost
  oci_instance:
    availability_domain: "{{ instance_ad }}"
    compartment_id: "{{ instance_compartment }}"
    name: "{{ env_name }}"
    image_id: "{{ instance_image }}"
    shape: "{{ instance_shape }}"
    vnic:
        assign_public_ip: false
        hostname_label: "{{ env_name }}"
        subnet_id: "{{ instance_subnet_id }}"
        private_ip: "{{ instance_ip }}"
    metadata:
        ssh_authorized_keys: "{{ lookup('file',  'files/pubkey' ) }}"
  register: result

- name: Print instance details
  delegate_to: localhost
  debug:
    msg: "Launched a new instance {{ result }}"

- set_fact:
    instance_id: "{{result.instance.id }}"

- name: Get the VNIC attachment details of instance
  delegate_to: localhost
  oci_vnic_attachment_facts:
    compartment_id: "{{ instance_compartment }}"
    instance_id: "{{ instance_id }}"
  register: result

- name: Get details of the VNIC
  delegate_to: localhost
  oci_vnic_facts:
    id: "{{ result.vnic_attachments[0].vnic_id }}"
  register: result

- set_fact:
    instance_private_ip: "{{ result.vnic.private_ip }}"
    instance_public_ip: "{{ result.vnic.public_ip }}"

- name: Print the private ip of the newly launched instance
  delegate_to: localhost
  debug:
    msg: "Private IP of launched instance {{ instance_private_ip }}"

- name: Print the public ip of the newly launched instance
  delegate_to: localhost
  debug:
    msg: "Public IP of launched instance {{ instance_public_ip }}"

- name: "Create Instance Data Directory"
  delegate_to: localhost
  file:
    path: "{{ metadata_base_path }}"
    state: directory

- name: "Save Instance Facts"
  delegate_to: localhost
  template:
    src: "instance-facts.j2"
    dest: "{{ metadata_base_path }}/dns.yaml"
