---
- name: "Create a Standard E2 Shape"
  include_tasks: "e2_shape.yaml"
  when: "'VM.Standard2.' in instance_shape"

- name: "Create a Standard E3 Flex Shape"
  include_tasks: "e3flex_shape.yaml"
  when: "'VM.Standard.E3.Flex' in instance_shape"

- name: "Print instance details"
  delegate_to: localhost
  debug:
    msg: "Launched a new instance {{ create_result }}"

- set_fact:
    instance_private_ip: "{{ create_result.instance.primary_private_ip }}"

- name: "Create Instance Data Directory"
  delegate_to: localhost
  file:
    path: "{{ metadata_base_path }}"
    state: directory

- name: "Save Instance Facts"
  delegate_to: localhost
  template:
    src: "instance-facts.j2"
    dest: "{{ metadata_base_path }}/{{ server_name }}.yaml"
