---
- name: "Install Cloudflare Repo"
  yum:
    name: "railgun-stable"
    state: present

- name: "Install Railgun"
  yum:
    name: "railgun-stable"
    state: present

- name: "Configure Railgun Config"
  template:
    src: "railgun.conf.j2"
    dest: "/etc/railgun/railgun.conf"
    owner: "root"
    group: "root"
    lstrip_blocks: yes

- name: "Configure Memcache"
  template:
    src: "memcached.j2"
    dest: "/etc/sysconfig/memcached"
    owner: "root"
    group: "root"
    lstrip_blocks: yes

- name: "Restart Memcached"
  service:
    name: "memcached"
    state: restarted

- name: "Restart Railgun"
  service:
    name: "railgun"
    state: restarted
    enabled: yes
