---
- hosts:
    - corp
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name | default(default_server_name) }}"
    instance_ad: "{{ arg_instance_ad }}"
    instance_shape: "{{ arg_instance_shape | default(default_instance_shape) }}"
    jenkins_user: "{{ arg_jenkins_user }}"
    instance_image: "{{ arg_instance_image | default(default_instance_image) }}"
    # instance_cpu and instance_memory are required when creating an E3.Flex shape
    instance_cpu: "{{ arg_instance_cpu | default('default_instance_cpu') }}"
    instance_memory: "{{ arg_instance_memory | default('default_instance_memory') }}"
    instance_role: "{{ arg_instance_role }}"
  roles:
    - common.oci-vars
    - common.vault-get-secrets
    - oci-create-instance
    - common.ssh-wait
