---
- hosts:
    - dev_primary
    - qa_primary
    - uat_primary
    - shared_primary
  become: yes
  become_user: root
  vars:
    record: "{{ arg_record }}"
  roles:
    - remove-dns-internal
    
