---
- hosts:
    - localhost
  vars:
    record_name: "{{ arg_record_name }}"
    record_type: "{{ arg_record_type }}"
    record_value: "{{ arg_record_value }}"
  roles:
    - vault-get-provisioner-token #Common Role
    - update-dns-dnsmadeeasy
