---
#OCI Configuration
ansible_ssh_user: "opc" #Use your default OCI user
ansible_ssh_private_key_file: "~/.ssh/oci_private_key" #Private Key created for SSH access into OCI
default_server_name: "static"
instance_ad: "sSxD:US-ASHBURN-AD-1"
instance_image: "ocid1.image.oc1.iad.aaaaaaaabip6l5i5ikqsnm64xwrw2rrkj3tzo2dv47frowlt3droliwpvfaa" # OCID for Oracle Linux 7 in Ashburn
instance_shape: "VM.StandardE2.1"
instance_hostname: "{{ env_name }}-{{ server_name }}"
metadata_base_path: "/home/tomcat/instances/{{ env_type }}/{{ env_name }}/"

cdn_url: "{{ env_name }}cdn.TLD.com"

#Instance Configuration
firewall_allow_ports:
  - "80/tcp"
  - "443/tcp"
