---
ansible_ssh_user: "opc"
ansible_ssh_private_key_file: "~/.ssh/oci_private_key"

default_server_name: "couchbase"
default_instance_image: "{{ regions.ashburn.default_images.ol7_ocid }}"
instance_hostname: "{{ env_name }}-{{ server_name }}"

default_bucket_ramsize: "6000"

metadata_base_path: "/home/tomcat/instances/{{ env_type }}/{{ env_name }}/"

firewall_allow_ports:
  - "4369/tcp"
  - "8091-8094/tcp"
  - "9100-9105/tcp"
  - "9110-9118/tcp"
  - "9120-9122/tcp"
  - "9130/tcp"
  - "9999/tcp"
  - "11209-11211/tcp"
  - "21100-21101/tcp"

couchbase_cli_environment:
  CB_REST_USERNAME: "{{ secrets.couchbase_user }}"
  CB_REST_PASSWORD: "{{ secrets.couchbase_password }}"
