---
- name: "Check if machine is already bound"
  shell: "/bin/bash -c 'realm list | grep sssd'"
  register: realmd_bound
  changed_when: false
  ignore_errors: true

- name: "Join system to AD"
  expect:
    command: "/bin/bash -c '/usr/sbin/realm join corp.ezrez --user={{ bind_name }}'"
    responses:
      (?i)Password for *: "{{ bind_pass }}"
    timeout: 300
  when: realmd_bound is failed

- name: "Add sudoers"
  template: 
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/{{ item.dest_config }}"
    owner: "root"
    group: "root"
    lstrip_blocks: yes
  with_items: "{{ commmon_realmd_sudo_config }}"

- name: "Modify SSSD Configuration"
  copy: 
    src: "sssd.conf"
    dest: "/etc/sssd/sssd.conf"
    
- name: "Restart SSSD Service"
  service: 
    name: "sssd"
    state: restarted

- name: "Modify SSH Configuration"
  copy: 
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
  timeout: 300

- name: "Restart SSH Service"
  service:
    name: "sshd"
    state: restarted
