---
- name: "Check if machine is already bound"
  shell: /bin/bash -c "realm list | grep sssd"
  register: realmd_bound
  changed_when: false
  ignore_errors: true

- name: "Join system to AD"
  expect:
    command: "/bin/bash -c '/usr/sbin/realm join domain --user={{ bind_name }}'"
    responses:
      (?i)Password for *: "{{ bind_pass }}"
    timeout: 300
  when: realmd_bound is failed

- name: "Add sudoers"
  copy: 
    src: "sudoers"
    dest: "/etc/sudoers.d/sudoers"

- name: "Modify SSSD Configuration"
  copy: 
    src: "sssd.conf"
    dest: "/etc/sssd/sssd.conf"
    
- name: "Restart SSSD Service"
  service: 
    name: "sssd"
    state: restarted

- name: "Modify SSH Configuration"
  copy: 
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"

- name: "Restart SSH Service"
  service:
    name: "sshd"
    state: restarted
