---
- hosts:
    - qa
    - uat
  become: yes
  become_user: root
  vars:
    - env_type: "{{ arg_env_type }}"
    - env_name: "{{ arg_env_name }}"
    - server_name: "{{ arg_server_name }}"
  roles:
    - firewall
    - java
    - elasticsearch
    - kibana
    - nginx
    - logstash
    - common-realmd-install
    - common-realmd-configure
    - metricbeat
