---
- hosts:
    - localhost
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name }}"
  roles:
    - oci-destroy-instance
  environment:
    OCI_ANSIBLE_AUTH_TYPE: "instance_principal"

    