---
ansible_ssh_user: "opc"
ansible_ssh_private_key_file: "~/.ssh/oci_private_key"

default_server_name: "checkmk"
instance_ad: "sSxD:US-ASHBURN-AD-1"
instance_compartment: "{{ compartments.shared.compartment_ocid }}"
default_instance_image: "{{ regions.ashburn.default_images.ol7_ocid }}"
instance_shape: "VM.Standard.E2.1"
instance_hostname: "{{ env_name }}-{{ server_name }}"
checkmk_hostname: "{{ env_name }}-{{ cmkhost_name }}"
instance_subnet_id: "{{ regions.ashburn.shared.vcn.subnets.ctr_ocid }}"
domain: "{{ env_type }}.ash.oci.ezrez"
metadata_base_path: "/home/tomcat/instances/{{ env_type }}/{{ env_name }}/"

firewall_allow_ports: 
  - "22/tcp"
  - "80/tcp"
  - "6556/tcp"
