---
- name: "Check Environment Details Exist"
  stat:
    path: "{{ metadata_base_path }}/{{ server_name }}.yaml"
  register: env_stat

- name: "Fail if Environment Stats Don't Exist"
  fail:
    msg: "{{ env_name }} does not exist"
  when: env_stat.stat.exists == false

- name: "Lookup Instance Facts"
  include_vars:
    file: "{{ metadata_base_path }}/{{ server_name }}.yaml"

- name: "Output Instance Facts"
  debug:
    msg: "{{ instance }}"

- name: "Terminate the Instance"
  oci_instance:
    auth_type: "instance_principal"
    id: "{{ instance.id }}"
    state: "absent"

- name: "Remove the Instance Data"
  file:
    path: "{{ metadata_base_path }}/{{ server_name }}.yaml"
    state: "absent"
