---
- hosts:
    - localhost
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name | default(default_server_name) }}"
  roles:
    - destroy-oci
  environment:
    OCI_ANSIBLE_AUTH_TYPE: "instance_principal"

    