---
- hosts:
    - shared
  become: yes
  become_user: root
  vars:
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name }}"
  roles:
    - mounts
    - common.vault-get-secrets
    - common.realmd-install
    - common.realmd-configure
