---
- hosts:
    - dev
    - qa
    - uat
  become: yes
  become_user: root
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
  roles:
    - common-vault-get-secrets
    - configure-cluster
    - common-realmd-configure
  environment: "{{ couchbase_cli_environment }}"

- hosts:
    - prod
  become: yes
  become_user: root
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
  roles:
    - common-vault-get-secrets
    - configure-cluster
  environment: "{{ couchbase_cli_environment }}"
