---
- hosts:
    - qa
    - uat
    - prod
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name | default(default_server_name) }}"
    instance_ad: "{{ arg_instance_ad }}"
    instance_shape: "{{ arg_instance_shape }}"
    jenkins_user: "{{ arg_jenkins_user }}"
    instance_image: "{{ arg_instance_image | default(regions.ashburn.default_images.ol7_ocid) }}"
    # instance_cpu and instance_memory are required when creating an E3.Flex shape
    instance_cpu: "{{ arg_instance_cpu | default('') }}"
    instance_memory: "{{ arg_instance_memory | default('') }}"
  roles:
    - oci-vars
    - common-vault-get-secrets
    - create-oci
    - common-ssh-wait
  environment:
    OCI_ANSIBLE_AUTH_TYPE: "instance_principal"
