---
- hosts:
    - dev
    - qa
    - uat
    - prod
  become: yes
  become_user: root
  vars:
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name | default(default_server_name) }}"
  roles:
    - delete-bucket
