---
- hosts:
    - dev
    - qa
    - uat
    - prod
  become: yes
  become_user: root
  vars:
    env_name: "{{ arg_env_name }}"
    bucket_ramsize: "{{ arg_bucket_ramsize | default(default_bucket_ramsize) }}"
    server_name: "{{ arg_server_name | default(default_server_name) }}"
  roles:
    - common-vault-get-secrets
    - make-bucket
