---
- name: "Remove Cloudflare A Record"
  cloudflare_dns:
    zone: "MY.TLD.COM"
    type: A
    record: "{{ record_name }}"
    value: "{{ record_value }}"
    state: absent
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_key }}"
    