---
- name: "Get instance facts"
  oracle.oci.oci_compute_boot_volume_attachment_facts:
    instance_id: "{{ instance_id }}"
    compartment_id: "{{ compartment_id }}"
    availability_domain: "{{ ad_id }}"
  register: instance_facts_result
  delegate_to: localhost

- name: "Print instance facts"
  debug:
    var: instance_facts_result.boot_volume_attachments[0].boot_volume_id

- name: "Pet boot volume backup policy" ##Sets backup policy for target boot volume
  oracle.oci.oci_blockstorage_volume_backup_policy_assignment:
    asset_id: "{{ instance_facts_result.boot_volume_attachments[0].boot_volume_id }}"
    policy_id: "{{ backup_policy[policy_type] }}" #policy_type variable from pipeline
  delegate_to: localhost
