---
ansible_ssh_user: "opc"
ansible_ssh_private_key_file: "~/.ssh/oci_private_key"

default_server_name: "splunk"
instance_ad: "sSxD:US-ASHBURN-AD-1"
instance_compartment: "{{ compartments.shared.compartment_ocid }}" #shared Compartment
default_instance_image: "{{ regions.ashburn.default_images.ol7_ocid }}"
instance_shape: "VM.Standard.E2.1"
instance_hostname: "{{ env_name }}-{{ server_name }}"
instance_subnet_id: "{{ regions.ashburn.shared.vcn.subnets.ctr_ocid }}" #CRT Subnet
domain: "{{ env_type }}.ash.my.domain"
metadata_base_path: "/home/tomcat/instances/{{ env_type }}/{{ env_name }}/"

firewall_allow_ports: 
  - "8000/tcp"
  - "22/tcp"
  - "80/tcp"
  - "9997/tcp"
  - "8089/tcp"