---
- name: "Launch an instance"
  delegate_to: localhost
  oci_instance:
    availability_domain: "{{ instance_ad }}"
    compartment_id: "{{ instance_compartment }}"
    name: "{{ env_name }}-{{ server_name }}"
    image_id: "{{ instance_image }}"
    shape: "{{ instance_shape }}"
    vnic:
      assign_public_ip: false
      hostname_label: "{{ instance_hostname }}"
      subnet_id: "{{ instance_subnet_id }}"
    metadata:
      ssh_authorized_keys: "{{ lookup('file',  'files/pubkey' ) }}"
    defined_tags: {
        'Common': {
          'CreatedBy': "{{ jenkins_user }}",
          'EnvironmentType': "{{ env_type }}",
          'EnvironmentName': "{{ env_name }}",
        },
        'Instances': {
          'ServerType': "checkmk",
          'ServerName': "{{ server_name }}",
        }
      }
  register: create_result

- name: "Print instance details"
  delegate_to: localhost
  debug:
    msg: "Launched a new instance {{ create_result }}"

- name: "Create Instance Data Directory"
  delegate_to: localhost
  file:
    path: "{{ metadata_base_path }}"
    state: directory

- name: "Save Instance Facts"
  delegate_to: localhost
  template:
    src: "instance-facts.j2"
    dest: "{{ metadata_base_path }}/{{ server_name }}.yaml"
