---
- hosts:
    - uat
    - shared
  become: yes
  become_user: root
  vars:
    env_type: "{{ arg_env_type }}"
    env_name: "{{ arg_env_name }}"
    server_name: "{{ arg_server_name }}"
  roles:
    - common.vault-get-secrets
    - users
    - common.firewall
    - mounts
    - nginx
    - parallel-file-tools
    - common.realmd-install
    - common.realmd-configure
