---
- name: "Vault Login"
  shell:
    cmd: "/usr/local/bin/vault login -method=oci auth_type=instance role=provisioner-role -format=json"
  register: vault_login_result
  environment:
    VAULT_ADDR: "{{ vault_url }}"
  become: false
  delegate_to: localhost


- name: "Vault Token"
  set_fact:
    vault_token: "{{ vault_login_result.stdout | from_json | json_query('auth.client_token') }}"
