---
- name: "Output use_tx_pool_mode"
  debug:
    msg: "{{ use_tx_pool_mode }}"

- name: "Install pgbouncer.ini"
  template:
    src: "pgbouncer_{{ env_type }}.ini.j2"
    dest: "/etc/pgbouncer/pgbouncer.ini"
    lstrip_blocks: yes
  notify: "restart pgbouncer"
